### ISSUE TITLE
Missing closing parentheses on CSS colors

### ISSUE THREAD

**Issue by tragessere** [Purdue/purdue-wp-theme#106]
In the functions.php file, the 'editor-color-palette' definition is missing closing parentheses on the Opaque and Transparent colors. This is breaking styling following those two variable declarations in the global-styles-inline-css style block.

First instance is here: https://github.com/Purdue/purdue-wp-theme/blob/master/functions.php#L507

The next instance is a few lines below it.

**Comment by Yanhuazong** [comment]
Thank you. The typos have been fixed. Thanks very much!
